### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by aikram24** [erikh/hubot-pagerduty#7]
[Thu Feb 18 2016 11:32:13 GMT-0500 (EST)] ERROR TypeError: Cannot read property 'entries' of null
  at /opt/pagerduty/node_modules/hubot-pagerduty/src/scripts/pagerduty.coffee:88:18, <js>:85:52
  at ClientRequest.<anonymous> (/opt/pagerduty/node_modules/scoped-http-client/src/index.js:99:20)
  at ClientRequest.emit (events.js:95:17)
  at CleartextStream.socketErrorListener (http.js:1548:9)
  at CleartextStream.emit (events.js:95:17)
  at SecurePair.<anonymous> (tls.js:1400:19)
  at SecurePair.emit (events.js:92:17)
  at SecurePair.maybeInitFinished (tls.js:980:10)
  at CleartextStream.read [as _read] (tls.js:472:13)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at EncryptedStream.write [as _write] (tls.js:369:25)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at Socket.pipeOnReadable (_stream_readable.js:643:5)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)

**Comment by erikh** [comment]
Ah ok; this is a bug in 
https://github.com/erikh/hubot-pagerduty/blob/master/src/scripts/pagerduty.coffee#L79-L88 
-- could you provide a patch for it? I am rather busy these days and 
don't use this code any more.
